[2025-03-19T19:07:28.410+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T19:07:29.416+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_Api_v2.greet scheduled__2024-11-27T00:00:00+00:00 [queued]>
[2025-03-19T19:07:29.520+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_Api_v2.greet scheduled__2024-11-27T00:00:00+00:00 [queued]>
[2025-03-19T19:07:29.521+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T19:07:29.816+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 2024-11-27 00:00:00+00:00
[2025-03-19T19:07:29.970+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10069) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T19:07:30.043+0000] {standard_task_runner.py:72} INFO - Started process 10098 to run task
[2025-03-19T19:07:30.154+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_Api_v2', 'greet', 'scheduled__2024-11-27T00:00:00+00:00', '--job-id', '2922', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmpqyl62pcf']
[2025-03-19T19:07:30.349+0000] {standard_task_runner.py:105} INFO - Job 2922: Subtask greet
[2025-03-19T19:07:34.645+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_Api_v2.greet scheduled__2024-11-27T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T19:07:37.378+0000] {job.py:229} INFO - Heartbeat recovered after 11.70 seconds
[2025-03-19T19:07:40.523+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_Api_v2' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-11-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-27T00:00:00+00:00'
[2025-03-19T19:07:40.648+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T19:07:40.886+0000] {logging_mixin.py:190} INFO - Hello JohnDoe, you are 19 years old.
[2025-03-19T19:07:40.912+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-19T19:07:41.533+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T19:07:42.190+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_Api_v2, task_id=greet, run_id=scheduled__2024-11-27T00:00:00+00:00, execution_date=20241127T000000, start_date=20250319T190729, end_date=20250319T190742
[2025-03-19T19:07:44.988+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T19:07:45.456+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-19T19:07:45.431+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T19:07:45.495+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
