[2025-03-19T19:05:13.687+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T19:05:13.820+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_Api_v2.get_name scheduled__2024-09-22T00:00:00+00:00 [queued]>
[2025-03-19T19:05:13.861+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_Api_v2.get_name scheduled__2024-09-22T00:00:00+00:00 [queued]>
[2025-03-19T19:05:13.862+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T19:05:14.647+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): get_name> on 2024-09-22 00:00:00+00:00
[2025-03-19T19:05:14.773+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=9333) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T19:05:14.804+0000] {standard_task_runner.py:72} INFO - Started process 9357 to run task
[2025-03-19T19:05:14.791+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_Api_v2', 'get_name', 'scheduled__2024-09-22T00:00:00+00:00', '--job-id', '2706', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmpthic_u7a']
[2025-03-19T19:05:14.871+0000] {standard_task_runner.py:105} INFO - Job 2706: Subtask get_name
[2025-03-19T19:05:15.768+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_Api_v2.get_name scheduled__2024-09-22T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T19:05:17.611+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_Api_v2' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-09-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-22T00:00:00+00:00'
[2025-03-19T19:05:17.718+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T19:05:17.802+0000] {python.py:240} INFO - Done. Returned value was: {'first_name': 'John', 'last_name': 'Doe'}
[2025-03-19T19:05:18.596+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T19:05:18.623+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_Api_v2, task_id=get_name, run_id=scheduled__2024-09-22T00:00:00+00:00, execution_date=20240922T000000, start_date=20250319T190513, end_date=20250319T190518
[2025-03-19T19:05:19.538+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T19:05:19.879+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-19T19:05:19.924+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
