[2025-03-19T19:23:17.964+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T19:23:18.709+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_taskflow_Api_v2.get_name scheduled__2024-12-29T00:00:00+00:00 [queued]>
[2025-03-19T19:23:19.256+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_taskflow_Api_v2.get_name scheduled__2024-12-29T00:00:00+00:00 [queued]>
[2025-03-19T19:23:19.341+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 6
[2025-03-19T19:23:20.000+0000] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): get_name> on 2024-12-29 00:00:00+00:00
[2025-03-19T19:23:21.890+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10558) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T19:23:22.278+0000] {standard_task_runner.py:72} INFO - Started process 10581 to run task
[2025-03-19T19:23:22.233+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'dag_with_taskflow_Api_v2', 'get_name', 'scheduled__2024-12-29T00:00:00+00:00', '--job-id', '3027', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_taskflow_api.py', '--cfg-path', '/tmp/tmpr6ku1w0d']
[2025-03-19T19:23:22.483+0000] {standard_task_runner.py:105} INFO - Job 3027: Subtask get_name
[2025-03-19T19:27:29.564+0000] {job.py:229} INFO - Heartbeat recovered after 259.31 seconds
[2025-03-19T19:27:33.184+0000] {task_command.py:467} INFO - Running <TaskInstance: dag_with_taskflow_Api_v2.get_name scheduled__2024-12-29T00:00:00+00:00 [running]> on host 63fd4b143e0a
[2025-03-19T19:27:39.314+0000] {job.py:229} INFO - Heartbeat recovered after 11.76 seconds
[2025-03-19T19:27:57.227+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dag_with_taskflow_Api_v2' AIRFLOW_CTX_TASK_ID='get_name' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-29T00:00:00+00:00'
[2025-03-19T19:27:57.809+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T19:27:58.291+0000] {python.py:240} INFO - Done. Returned value was: {'first_name': 'John', 'last_name': 'Doe'}
[2025-03-19T19:27:59.732+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T19:27:59.747+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=dag_with_taskflow_Api_v2, task_id=get_name, run_id=scheduled__2024-12-29T00:00:00+00:00, execution_date=20241229T000000, start_date=20250319T192318, end_date=20250319T192759
[2025-03-19T19:28:09.097+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-19T19:28:15.540+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-19T19:28:21.595+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
